### PR TITLE
Rebuild after SSH deploy key update

### PR DESCRIPTION
**Pull request by hoechenberger**
Deploy key was updated in GH-4.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@kastman It seems that the CircleCI build [failed](https://circleci.com/gh/conda-forge/pyosf-feedstock/12) due to network connectivity issues, is it possible to simply restart the build? Or will I have to push again, increasing the build number?

**Comment by hoechenberger** [comment]
@kastman Friendly ping :)

**Comment by kastman** [comment]
I missed the link the first time; no good. I think I can recommit this with a force push — I’ll look first thing tomorrow morning!

**Comment by hoechenberger** [comment]
No worries, I already suspected that – I keep deleting entire Github threads myself (and, therefore, sometimes missing messages) as the flood of emails is sometimes just too big! Thanks for looking into this!

**Pull request merged**
